export const people = [
	{ name: "Alice Johnson", job_title: "Software Engineer" },
	{ name: "Bob Smith", job_title: "Data Scientist" },
	{ name: "Charlie Brown", job_title: "Product Manager" },
	{ name: "Diana Prince", job_title: "UX/UI Designer" },
	{ name: "Ethan Hunt", job_title: "DevOps Engineer" },
	{ name: "Fiona Gallagher", job_title: "Frontend Developer" },
	{ name: "George Martin", job_title: "Backend Developer" },
	{ name: "Hannah Baker", job_title: "QA Engineer" },
	{ name: "Ian Fleming", job_title: "Security Analyst" },
	{ name: "Jane Doe", job_title: "Technical Writer" },
	{ name: "Kevin Hart", job_title: "IT Support Specialist" },
	{ name: "Laura Palmer", job_title: "Database Administrator" },
	{ name: "Michael Scott", job_title: "Project Manager" },
	{ name: "Nina Simone", job_title: "Business Analyst" },
	{ name: "Oscar Wilde", job_title: "Content Strategist" },
	{ name: "Paul Atreides", job_title: "Cloud Architect" },
	{ name: "Quincy Jones", job_title: "Network Engineer" },
	{ name: "Rachel Green", job_title: "Marketing Specialist" },
	{ name: "Steve Rogers", job_title: "Systems Administrator" },
	{ name: "Tina Turner", job_title: "Scrum Master" },
	{ name: "Uma Thurman", job_title: "Mobile Developer" },
	{ name: "Victor Hugo", job_title: "AI/ML Engineer" },
	{ name: "Wendy Darling", job_title: "Customer Success Manager" },
	{ name: "Xander Cage", job_title: "Solutions Architect" },
	{ name: "Yara Shahidi", job_title: "Sales Engineer" },
	{ name: "Zane Grey", job_title: "Full Stack Developer" },
	{ name: "Ava Gardner", job_title: "Data Engineer" },
	{ name: "Bruce Wayne", job_title: "Chief Technology Officer (CTO)" },
	{ name: "Clara Oswald", job_title: "HR Manager" },
	{ name: "David Tennant", job_title: "Software Architect" },
	{ name: "Elena Gilbert", job_title: "Digital Marketing Manager" },
	{ name: "Frank Underwood", job_title: "Operations Manager" },
	{ name: "Gina Linetti", job_title: "Office Manager" },
	{ name: "Harry Potter", job_title: "Junior Developer" },
	{ name: "Isabella Swan", job_title: "SEO Specialist" },
	{ name: "Jack Sparrow", job_title: "IT Manager" },
	{ name: "Kara Danvers", job_title: "Social Media Manager" },
	{ name: "Liam Neeson", job_title: "Lead Developer" },
	{ name: "Mia Wallace", job_title: "Graphic Designer" },
	{ name: "Noah Centineo", job_title: "Customer Support Specialist" },
	{ name: "Olivia Pope", job_title: "Public Relations Manager" },
	{ name: "Peter Parker", job_title: "Junior Data Analyst" },
	{ name: "Quinn Fabray", job_title: "Financial Analyst" },
	{ name: "Ron Weasley", job_title: "Software Tester" },
	{ name: "Samantha Jones", job_title: "Account Manager" },
	{ name: "Tony Stark", job_title: "Chief Information Officer (CIO)" },
	{ name: "Ursula K. Le Guin", job_title: "Technical Support Engineer" },
	{ name: "Vin Diesel", job_title: "Hardware Engineer" },
	{ name: "Will Smith", job_title: "Innovation Manager" },
	{ name: "Xena Warrior", job_title: "Training and Development Manager" },
];
