import type { Metadata } from "next";
import "./globals.css";
import { blackSans } from "@/fonts";
import { Header } from "@/components/header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={blackSans.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
